export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";

export const COMPLETE_REGISTER_USER_REQUEST = "COMPLETE_REGISTER_USER_REQUEST";
export const COMPLETE_REGISTER_USER_SUCCESS = "COMPLETE_REGISTER_USER_SUCCESS";
export const COMPLETE_REGISTER_USER_FAIL = "COMPLETE_REGISTER_USER_FAIL";

export const POST_ENQUIRY_SUCCESS ="POST_ENQUIRY_SUCCESS";
export const POST_ENQUIRY_FAIL ="POST_ENQUIRY_FAIL";

